fuseumass/hackumass.github.io

v2/index.html
=> Updates text to index page

assets/css/style.css
Change the color to HackUmass IV Blue
=> change the color to blue

index.html
changed the "login" button to "go to dashboard"
=> changed login button

index.html
- Updated the popup to display that applications are open
- Added table for UMass + Non-UMass students
=> Updated the popup to display that applications are open

assets/css/style.css, index.html
**Changelog**:
- Added write-up from logistics to pop-up in `./index.html`
- Changed all paddings from em to rem for pop-up in `./index.html`
- Changed half-em-padding to half-rem-padding in `./assets/css/style.css`
=> Added write-up from logistics and refined CSS across pop-up

index.html
This PR is intended to fix #69.
- Fixed the hover color issue - added a missing closing brace for the previous CSS class
- Stylistic - changed the text color to white when hovering over the View Projects button
https://user-images.githubusercontent.com/20084950/139270661-d1c9ea03-4b00-41db-bc2e-0249991c2ecd.mov
=> Resolve hover color issue

index.html
This PR is intended to be an enhancement for #73, upon #74. 
- Restructured the "Applications Closed" popup to be consistent with the new popup layout used for earlier "Applications Open" popup
=> Made the applications closed popup consistent with the new popup layout

index.html
This PR is intended to fix #60.
- Uncommented the section for the MLH banner
=> Added the MLH banner again

.prettierrc, apply.html, assets/css/logo.css, assets/css/style.css, assets/css/thesaas.css, assets/js/isInViewport.js, assets/js/schedule.js, assets/js/script.js, assets/js/thesaas.js, index.html, maintenance.html, schedule.html
This PR is intended to fix #35 by utilizing the Prettier formatter with a defined configuration.
The Prettier configuration is stored in `.prettierc` as:
```JSON
{
"trailingComma": "all",
"tabWidth": 2,
"semi": true,
"singleQuote": true
}
```
- Added a Prettier configuration for formatting HTML, CSS, and JS
- Removed erroneous closing tags and formatted all `*.html` files
- Formatted all `*.css` files as per Prettier configuration, barring the minified ones of the form `*.min.css`
- Formatted all `*.js` files as per Prettier configuration, barring the minified ones of the form `*.min.js`
=> Establish formatting guidelines and fix formatting of current files

assets/css/style.css, assets/img/logo-universal.svg, index.html
This PR is intended to fix #84.
=> Update color around. 

index.html
This PR is intended to fix #87.
=> Updated event dates

index.html
intended to fix the MLH Badge.
=> MLH Badge Change part 2

index.html
Updates the FAQs section about HackUMass X's in-person and virtual components, participation criteria, non-UMass Amherst students participation, travel accommodations, etc.
=> Updated the FAQs section

index.html
Updated the List of Sponsors and Partners, with new logos and websites link.
=> Sponsors and partners

index.html
fixed the registration pop up, and centered it as well
=> 95 participant applications open popup

index.html
Underlining text, and making all links open in a new tab
=> Changing past projects link to hackumass vii

index.html
=> added dividing line

index.html
- 🎨Auto-format index.html
This PR is intended to fix #114
=> 🐛 Fix popup for mobile view.

index.html
This PR is intended to fix #118
=> 💄 Increase the size for mobile pop-up box.

index.html
This PR is intended to fix #120
=> 💄 Change Go To Dashboard to Register

index.html
=> Adding discord link to popup and homepage

index.html
This PR is intended to fix #124
=> View VII projects instead of IX (for now)

index.html
This PR is intended to fix #128
=> 💄 Improve UI

index.html
- 'Go To Dashboard' serves the same functionality.
=> Remove 'Register' button

index.html
This PR is intended to fix #123
=> Re-enable MLH badge back to homepage

index.html
- Remove travel reimbursement information from faqs
- Closes #141
=> Updating travel reimbursement info in faqs

index.html
changed accesibility for partners and meet ppl behind it
=> changed accesibility for partners and ppl behind

assets/css/style.css, index.html
This PR is intended to resolve #134 . Please let me know if there is any missing event.
=> Add schedule highlights to main page

index.html
FIxing schedule timings and changing some of the workshop titles
=> Fixing timings for schedule

index.html
=> Fixing scheduling typos

index.html
=> Fixing name of workshops

index.html
- Fixed judging time (to 12:00 PM, Sunday)
- Updated names for project submission deadlines
=> Minor fixes to HackUMass X Schedule

index.html
=> disabled event app popup and enabled organizer app

index.html
=> update new date

assets/css/style.css
=> updated colors

index.html
=> removed MLH logo

index.html
=> update meta data

index.html
=> updated Generous Sponsors section image

assets/css/style.css, assets/js/our-team-tab.js, index.html
=> changed member view from list to tabs

index.html
=> added mlh badge
